import { Permissions } from 'discord.js';

export enum PERMISSIONS {
    ADMINISTRATOR =                 Permissions.FLAGS.ADMINISTRATOR,
    CREATE_INSTANT_INVITE =         Permissions.FLAGS.CREATE_INSTANT_INVITE,
    KICK_MEMBERS =                  Permissions.FLAGS.KICK_MEMBERS,
    BAN_MEMBERS =                   Permissions.FLAGS.BAN_MEMBERS,
    MANAGE_CHANNELS =               Permissions.FLAGS.MANAGE_CHANNELS,
    MANAGE_GUILD =                  Permissions.FLAGS.MANAGE_GUILD,
    ADD_REACTIONS =                 Permissions.FLAGS.ADD_REACTIONS,
    VIEW_AUDIT_LOG =                Permissions.FLAGS.VIEW_AUDIT_LOG,
    PRIORITY_SPEAKER =              Permissions.FLAGS.PRIORITY_SPEAKER,
    VIEW_CHANNEL =                  Permissions.FLAGS.VIEW_CHANNEL,
    READ_MESSAGES =                 Permissions.FLAGS.READ_MESSAGES,
    SEND_MESSAGES =                 Permissions.FLAGS.SEND_MESSAGES,
    SEND_TTS_MESSAGES =             Permissions.FLAGS.SEND_TTS_MESSAGES,
    MANAGE_MESSAGES =               Permissions.FLAGS.MANAGE_MESSAGES,
    EMBED_LINKS =                   Permissions.FLAGS.EMBED_LINKS,
    ATTACH_FILES =                  Permissions.FLAGS.ATTACH_FILES,
    READ_MESSAGE_HISTORY =          Permissions.FLAGS.READ_MESSAGE_HISTORY,
    MENTION_EVERYONE =              Permissions.FLAGS.MENTION_EVERYONE,
    USE_EXTERNAL_EMOJIS =           Permissions.FLAGS.USE_EXTERNAL_EMOJIS,
    EXTERNAL_EMOJIS =               Permissions.FLAGS.EXTERNAL_EMOJIS,
    CONNECT =                       Permissions.FLAGS.CONNECT,
    SPEAK =                         Permissions.FLAGS.SPEAK,
    MUTE_MEMBERS =                  Permissions.FLAGS.MUTE_MEMBERS,
    DEAFEN_MEMBERS =                Permissions.FLAGS.DEAFEN_MEMBERS,
    MOVE_MEMBERS =                  Permissions.FLAGS.MOVE_MEMBERS,
    USE_VAD =                       Permissions.FLAGS.USE_VAD,
    CHANGE_NICKNAME =               Permissions.FLAGS.CHANGE_NICKNAME,
    MANAGE_NICKNAMES =              Permissions.FLAGS.MANAGE_NICKNAMES,
    MANAGE_ROLES =                  Permissions.FLAGS.MANAGE_ROLES,
    MANAGE_ROLES_OR_PERMISSIONS =   Permissions.FLAGS.MANAGE_ROLES_OR_PERMISSIONS,
    MANAGE_WEBHOOKS =               Permissions.FLAGS.MANAGE_WEBHOOKS,
    MANAGE_EMOJIS =                 Permissions.FLAGS.MANAGE_EMOJIS,
}